feat(arro3): Freethreading - module markers + CI
kylebarron/arro3 pull request #275
Opened 2024-12-16 09:38 UTC by H-Plus-Time

Yet another fork (this time in setup-python), what exactly was it about setup-uv in windows that broke builds?

Verified wheel building run over at https://github.com/H-Plus-Time/arro3/actions/runs/12349504140.

2024-12-16 14:12 UTC, kylebarron commented
I was hitting this https://github.com/kylebarron/arro3/pull/263

2024-12-16 15:30 UTC, kylebarron commented
It's also an issue that the buffer protocol is even less sound in Python 3.13t.

See discussion: https://discord.com/channels/1209263839632424990/1310572181138178129/1310572181138178129, https://alexgaynor.net/2022/oct/23/buffers-on-the-edge/, https://github.com/PyO3/pyo3/issues/2824

I'm not sure what to do here. It's very beneficial to _have_ the buffer protocol as an option. So perhaps just document to Python users that it's unsafe to mutate the Python buffer after passing it to rust?

2024-12-17 14:58 UTC, H-Plus-Time commented
Yeah -  I'm actually having a great deal of difficulty thinking of buffer protocol scenarios where freethreading would be unsound but not GIL-enabled; there's definitely a difference, but the complete lack of immutability guarantees is 99% of the problem (and serialized python execution (the GIL) addresses the remaining 1%).

I think the safety note on `into_arrow_array`, surfaced prominently should do the trick.

By the sounds of (amongst other parts of that document) https://py-free-threading.github.io/porting/#dealing-with-thread-unsafe-objects and the comments on how numpy is going ahead with this, pathological cases (like resizing an array while it's being read) can just be left as "you're holding it wrong, enjoy the segfault", right up until the first bug report.

2024-12-17 16:01 UTC, kylebarron commented
It would be nice if we didn't have to use a fork of `numpy`. Do you know if there's progress towards getting that merged?

2024-12-20 12:25 UTC, H-Plus-Time commented
> Hmm it looks like I can't trigger the wheel builds on this repo from your PR.

Yeah, I noticed that in my own fork, though that seems to be fine now :thinking:. It's likely a matter of: jobs can be triggered manually via workflow_dispatch, but not on pull requests (the wheels would need on: pull_request, which might be ok with cancel-in-progress); there doesn't seem to be a non-convoluted way to do manually triggered PR checks.

2024-12-20 13:21 UTC, H-Plus-Time commented
Mm, not yet, probably mid-January (given the whole Christmas/NYE period is upon us) - it looks like it's down to a single mutex, probably test reconfiguration too.

Obtrusiveness-wise, I can stick a (concise) spiel in the docstring of Array::frombuffer; I'd be hesitant to log anything at runtime higher than trace or debug level.

2025-02-11 17:25 UTC, kylebarron commented
I'm inclined not to merge this until numpy gets a stable release including the `free-threading` feature

2025-02-21 18:35 UTC, kylebarron commented
Numpy merged its free-threading pr: https://github.com/PyO3/rust-numpy/pull/471#event-16371763310

2025-02-23 00:25 UTC, H-Plus-Time commented
Excellent, hopefully shouldn't be too much longer until that gets a release. I'll re-pin to the tip of `main` and see if anything strange crops up in the build in the meantime.

2025-02-23 01:07 UTC, H-Plus-Time commented
Hrm, blocked by the pyO3 breaking change in 0.23.4 involving the `IntoPyObject` constraint and Chrono Tz. With the suggested workaround (`map(|v| v.fixed_offset())` specifically), seems to compile fine. By the looks of https://github.com/apache/arrow-rs/issues/7173 and associates, everything should pan out roughly around the same time (the numpy release + patch to obviate the `fixed_offset` workaround)

2025-02-23 02:08 UTC, kylebarron commented
> Hrm, blocked by the pyO3 breaking change in 0.23.4 involving the `IntoPyObject` constraint and Chrono Tz. 

Can you merge in latest main? It should be fixed.

2025-03-25 16:23 UTC, kylebarron commented on .github/workflows/wheels.yml
> +      - uses: Quansight-Labs/setup-python@v5
fwiw this is now supported by `actions/setup-python`

> FYI if anyone has been using quansight-labs/setup-python on github actions for free-threaded python CI or builds, action/setup-python finally released free-threaded support and we are winding down the fork - I’m going to send in PRs later today for public repos I can find on github search. 

https://discord.com/channels/1209263839632424990/1211072686545960980/1354069878973399183

https://github.com/PyO3/pyo3-async-runtimes/pull/38

2025-03-25 16:24 UTC, kylebarron commented
With https://github.com/kylebarron/arro3/pull/304 it looks like this might actually be unblocked?

2025-03-25 17:05 UTC, kylebarron commented on arro3-io/src/lib.rs
> +#[pymodule(gil_used = false)]
I'm not sure this will always be true for the IO module. E.g. I might want to allow a Python HTTP library like aiohttp to be used for making the `parquet` file reads

2025-03-25 23:28 UTC, H-Plus-Time commented
> With #304 it looks like this might actually be unblocked?

Oh, excellent - I gather the obstore py03 0.24.0 + object store 0.11 release unblocks this too (via #304 probably), right? That was my last blocker on this (the parquet crate's dependency on object store was involved in there somewhere).

2025-03-26 00:32 UTC, H-Plus-Time commented on arro3-io/src/lib.rs
> +#[pymodule(gil_used = false)]
True, if unmodified (as in, rust locking structures cfg-gated on `Py_GIL_DISABLED`) - there isn't code that allows that quite yet, right?

I should definitely take a crack at [pytest-freethread](https://github.com/tonybaloney/pytest-freethreaded) in general before this is merged (at the very least CI for a single test in pyo3-arrow or core).

Thinking about it, pretty much all users of the freethreading build at the moment are _other_ library maintainers porting their package to freethreading - this is probably a rare instance (especially given the main dependant is geoarrow.rust.io) where hard concurrency errors are preferred over `RuntimeWarning` .

2025-03-26 10:26 UTC, H-Plus-Time commented
Alright, interesting data so far: even without freethreading (and with the gil_used property stripped out) we already get concurrency errors :scream: in test_ipc (3/200 iterations). Reproducible in both debug and release builds, so I'm inclined to believe they're genuine.

With the gil_used flags set (oddly, despite the fact that this is still with the gil enabled), parquet kv metadata tests start throwing concurrency errors.

Actually running the tests against an 3.13t build does work, but it's far more sensitive (I ended up having to resort to a pixi equivalent of the uv environment, after encountering segfaults on mismatched ABIs (manylinux_2_17 vs manylinux_2_34)). The good news on that front is core and compute are (as expected) safe in freethreading (out of an abundance of caution, I've run it at 24 threads and 10k iterations, not a peep).

---

I think that answers it - we mark the IO tests as ineligible for concurrent tests and remove the gil_used attribute for arro3-io (importing it really *should* re-engage the GIL).

2025-03-26 23:26 UTC, H-Plus-Time commented
The IO test failures apply to both 3.13 and 3.13t (also probably all python versions that we build for).

In retrospect, I should have spotted it - it's the roundtrip test, so this:
```
    def test_ipc_round_trip_path():
        table = pa.table({"a": [1, 2, 3, 4]})
        write_ipc(table, Path("test.arrow"))
        table_retour = pa.table(read_ipc(Path("test.arrow")))
        assert table == table_retour
    
        write_ipc_stream(table, Path("test.arrows"))
>       table_retour = pa.table(read_ipc_stream(Path("test.arrows")))
```

That throws with an invalid, unable to fill buffer error, in pyarrow.

Of course that would fail eventually if you ran it concurrently on exactly the same file (whether through file paths or file descriptors), since there's very little stopping you from starting a read on a file currently being written to.

2025-03-27 04:19 UTC, kylebarron commented
Oh that makes sense. So there's likely nothing wrong with the library; that test just wasn't written with concurrency in mind.

2025-03-28 17:13 UTC, kylebarron commented
> * Re-add gil_used=false on the IO module (since it is _currently_ not dependent on the GIL).

I think #313 might already change that. Or at least, there are some functions that take in a `py: Python` token, and so those presumably would change this.

2025-07-02 16:36 UTC, bschoenmaeckers commented
What is the status on this? I’m happy to help move this forward.

2025-07-02 20:17 UTC, kylebarron commented
I don't know much about freethreading. I mostly want to ensure that it's not an additional maintenance burden.

2025-07-03 07:34 UTC, bschoenmaeckers commented
I can take a closer look if anything is still depending on the GIL if you want. 
> there are some functions that take in a py: Python token, and so those presumably would change this.
FYI, Using the `Python` token does not mean that a function is GIL dependent. It means it requires the python thread state to be initialised.

2025-09-09 16:20 UTC, bschoenmaeckers requested changes

2025-09-09 16:20 UTC, bschoenmaeckers commented on pyproject.toml
> +requires-python = ">=3.13"
This should be reverted before merging.

2025-09-09 16:41 UTC, kylebarron commented on pyproject.toml
> +requires-python = ">=3.13"
The top-level `pyproject.toml` is only for development. This change only means that to run the tests you need to be using 3.13+. 

I renamed this `name` to `"dev-environment"` to make that clearer.

Regardless, might not need to pin 3.13 here.

2025-09-09 16:46 UTC, kylebarron commented
According to [pytest-freethreaded](https://github.com/tonybaloney/pytest-freethreaded) it's also important to run with `pytest --require-gil-disabled`

When I run this locally with the GIL disabled I get a segfault, so something is wrong? @bschoenmaeckers do you have an idea?

```
> uv run --python 3.13t pytest --require-gil-disabled
==================================================================== test session starts ====================================================================
platform darwin -- Python 3.13.6, pytest-8.4.2, pluggy-1.6.0
rootdir: /Users/kyle/github/kylebarron/arro3
configfile: pyproject.toml
plugins: freethreaded-0.1.0
collecting ... Fatal Python error: Segmentation fault

Current thread 0x00000002043560c0 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1320 in create_module
  File "<frozen importlib._bootstrap>", line 813 in module_from_spec
  File "<frozen importlib._bootstrap>", line 921 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "/Users/kyle/github/kylebarron/arro3/arro3-compute/python/arro3/compute/__init__.py", line 2 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1026 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "/Users/kyle/github/kylebarron/arro3/tests/compute/test_aggregate.py", line 3 in <module>
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/assertion/rewrite.py", line 186 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1387 in _gcd_import
  File "/Users/kyle/.local/share/uv/python/cpython-3.13.6+freethreaded-macos-aarch64-none/lib/python3.13t/importlib/__init__.py", line 88 in import_module
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/pathlib.py", line 587 in import_path
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/python.py", line 498 in importtestmodule
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/python.py", line 551 in _getobj
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/python.py", line 280 in obj
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/python.py", line 567 in _register_setup_module_fixture
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/python.py", line 554 in collect
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/runner.py", line 389 in collect
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/runner.py", line 344 in from_call
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/runner.py", line 391 in pytest_make_collect_report
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/pluggy/_callers.py", line 121 in _multicall
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/pluggy/_hooks.py", line 512 in __call__
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/runner.py", line 567 in collect_one_node
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/main.py", line 839 in _collect_one_node
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/main.py", line 974 in genitems
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/main.py", line 979 in genitems
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/main.py", line 979 in genitems
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/main.py", line 979 in genitems
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/main.py", line 813 in perform_collect
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/main.py", line 353 in pytest_collection
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/pluggy/_callers.py", line 121 in _multicall
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/pluggy/_hooks.py", line 512 in __call__
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/main.py", line 342 in _main
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/main.py", line 289 in wrap_session
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/main.py", line 336 in pytest_cmdline_main
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/pluggy/_callers.py", line 121 in _multicall
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/pluggy/_hooks.py", line 512 in __call__
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/config/__init__.py", line 175 in main
  File "/Users/kyle/github/kylebarron/arro3/.venv/lib/python3.13t/site-packages/_pytest/config/__init__.py", line 201 in console_main
  File "/Users/kyle/github/kylebarron/arro3/.venv/bin/pytest", line 10 in <module>
```

2025-09-09 17:07 UTC, kylebarron commented
Now I'm able to reproduce the segfault on CI as well https://github.com/kylebarron/arro3/actions/runs/17590097733/job/49968516771?pr=275

cc @H-Plus-Time as well

2025-09-09 17:13 UTC, bschoenmaeckers commented
I’m not entirely sure what happens here without a debug build of python. Does this error also occur on 3.14?

2025-09-09 18:38 UTC, kylebarron commented
> Does this error also occur on 3.14?

I tried

```
uv run --python 3.14t pytest --require-gil-disabled
```

But that doesn't work out of the box because pyarrow doesn't have a built wheel for 3.14t and I don't want to figure out how to build it. We could split out the tests to not require pyarrow but I don't have time to do that now.

2025-10-03 13:28 UTC, kylebarron commented
I updated package versions (esp maturin) and now CI seems to pass 🤷‍♂️.

Thanks all for your work here!

2025-10-03 13:28 UTC, kylebarron approved these changes

2025-10-03 13:29 UTC, merged